### ISSUE TITLE
Change page using navigate

### ISSUE THREAD

**Issue by alexey13** [WebReflection/a-route#1]
Good day, Andrea!
For now, there is only one way to change the path is by click on a-route element, app.navigate(path) does not change the path. I think the logic of pushstate https://github.com/WebReflection/a-route/blob/master/esm/index.js#L117 could be in navigate function and that will allow changing the page by using navigate function. What do you think? I can make a pr

onEvent () {
  dosomething...
  app.navigate(path)//will not change the page now, need to call pushstate manually
}

**Comment by WebReflection** [comment]
the history is handled on `a-route` link clicks:
https://github.com/WebReflection/a-route/blob/master/esm/index.js#L108-L119

changing it on navigate would interfere with the popstate handler:
https://github.com/WebReflection/a-route/blob/master/esm/index.js#L124-L127

maybe navigate should have a second parameter such as `noHistoryPush` for the latter case?

**Comment by alexey13** [comment]
maybe navigate should have a second parameter such as noHistoryPush for the latter case?

Yes, that's a good option for the case with the manual change of page.

**Comment by WebReflection** [comment]
Major version it is then:

  * `app.navigate(path)` now pushes to the history
  * `app.navigate(path, 'replace')` replaces to the history
  * `app.navigate(path, 'ignore')` or `'noop'` or anything else that is not `push` or `replace`, will not do anything

I hope this works well 👋

**Comment by alexey13** [comment]
👍
